version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: whats_happening_db
    environment:
      POSTGRES_DB: whats_happening
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    restart: always